name: Push Feature to Develop
run-name: ${{ github.actor }} execute PR to Develop 🚀
on:
  push:
    branches:
      - develop
      - 'feature/**'
jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".java"
  Test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
	        ref: ${{ github.head_ref || github.ref_name }} 
      - name: Output results
        id: output-results
        run: |
          echo ${{ matrix.paths }}            
      - name: Content
        id: output-content
        run: |
          content=`cat ${{ matrix.paths }}`
          echo "::set-output name=file::$content"
      - run: |
          echo "${{steps.output-content.outputs.file}}"          