name: Push Feature to Develop
run-name: ${{ github.actor }} execute PR to Develop 🚀
on:
  push:
    branches:
      - develop
      - 'feature/**'
jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".java"
  Test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Output results
        run: |
          echo ${{ matrix.paths }}           
      # - name: Print
      #   run: |
      #     echo ${{ needs.list-files.outputs.paths }}       
      - name: Content
        run: |
          cat ${{ matrix.paths }}