name: Push Feature to Develop
run-name: ${{ github.actor }} execute PR to Develop 🚀
on:
  push:
    branches:
      - develop
      - 'feature/**'
jobs:
  identify-changed-files:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run which-files-changed
          uses: BuddhikaGeasman/which-files-changed@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            pr-comment: 'true' # or 'false' to control where to add the changes